apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
    tier: front
  name: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  strategy:
    rollingUpdate:
      type: "Recreate"
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vote
        tier: front
    spec:
      containers:
      - image: schoolofdevops/vote:xxx
        name: vote
        resources: {}
status: {}
