apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: worker
  name: worker
spec:
  minReadySeconds: 20
  replicas: 2
  template:
    spec:
      containers:
      - image:  schoolofdevops/worker:latest
        name: worker
